name: built_json
version: 0.0.4
description: >
  JSON serialization for Built Collections, Built Values and Enum Classes.
  This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_json.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'
  quiver: '>=0.21.0 <0.22.0'

dev_dependencies:
  test: any
