name: built_json_generator
version: 0.0.3
description: >
  JSON serialization for Built Collections, Built Values and Enum Classes.
  This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_json.dart

environment:
  sdk: '>=1.12.0-dev.5.10 <2.0.0'

dependencies:
  analyzer: '>=0.26.1 <1.0.0'
  built_collection: '^1.0.0'
  built_json: '^0.0.3'
  source_gen: '>=0.4.3 <0.5.0'
  quiver: '>=0.21.0 <0.22.0'

dev_dependencies:
  built_value: '^0.0.4'
  built_value_generator: '^0.0.4'
  test: any
